parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            #Symfony\Component\Workflow\StateMachine $trafficLightStateMachine: '@state_machine.traffic_light'
            Symfony\Component\Workflow\Workflow $articleWorkflow: '@workflow.article'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    App\Command\WorkflowUpdateSvgCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    state_machine.traffic_light_php:
        public: true
        class: Symfony\Component\Workflow\StateMachine
        factory: [ App\Workflow\TrafficLightFactory, create ]

sensio_framework_extra:
    router:
        annotations: false
